version: '2'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: e_metrobus_production_django
    expose:
    - "5000"
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start
    networks:
    - emetrobus_network
    - caddy_network

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: e_metrobus_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres
    networks:
    - emetrobus_network

  redis:
    image: redis:5.0
    networks:
    - emetrobus_network

networks:
  emetrobus_network:
  caddy_network:
    external:
      name: docker_caddy_network
